# GitHub Actions workflow for standard Continuous Integration on push/PR.
name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-matrix:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    uses: ./.github/workflows/test.yml
    with:
      python-version: ${{ matrix.python-version }}
